
FROM tomcat:9.0
RUN rm -rf /usr/local/tomcat/webapps/*
COPY ~/.m2/repository/com/example1/demo1/0.0.1-SNAPSHOT/demo1-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
#COPY /home/runner/.m2/repository/com/example1/demo1/0.0.1-SNAPSHOT/demo1-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
#COPY demo1-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080
CMD ["catalina.sh", "run"]

