---
- name: Ensure backup directory exists
  file:
    path: "{{ backup_dir }}"
    state: directory

- name: Stop JBoss service
  shell: "/opt/jboss-as-6.0.0.Final/bin/shutdown.sh -S"
  become_user: jboss
  environment:
    JAVA_HOME: "{{ java_home }}"
    JBOSS_HOME: "{{ jboss_home }}"

- name: Stop JBoss server # this can be run with jboss-cli 
  shell: "/opt/jboss/bin/jboss-cli.sh --connect --controller={{ jboss.host }}:{{ jboss.port }} --command='/shutdown'"
  become_user: jboss
  environment:
    JAVA_HOME: "{{ java_home }}"
    JBOSS_HOME: "{{ jboss_home }}"


- name: Backup current deployment
  copy:
    src: "{{ deploy_dir }}/{{ war_file_name }}"
    dest: "{{ backup_dir }}/{{ war_file_name }}_{{ ansible_date_time.iso8601 }}.war"
    remote_src: yes

- name: Remove current WAR file
  file:
    path: "{{ deploy_dir }}/{{ war_file_name }}"
    state: absent

- name: Copy new WAR file
  copy:
    src: "roles/jboss_deploy/files/{{ war_file_name }}"
    dest: "{{ deploy_dir }}/{{ war_file_name }}"

- name: Stop JBoss service
  shell: "/opt/jboss-as-6.0.0.Final/bin/run.sh"
  environment:
    JAVA_HOME: "{{ java_home }}"
    JBOSS_HOME: "{{ jboss_home }}"

