---
- name: Ensure backup directory exists
  file:
    path: "{{ backup_dir }}"
    state: directory

# jboss-cli.sh --controller=localhost:9990 --connect --command=shutdown
- name: Stop JBoss service
  shell: "/opt/jboss/bin/jboss-cli.sh --controller=localhost:9990 --connect --command=shutdown"
  become_user: jboss
  ignore_errors: yes
  environment:
    JAVA_HOME: "{{ java_home }}"
    JBOSS_HOME: "{{ jboss_home }}"

- name: Backup current deployment
  copy:
    src: "{{ deploy_dir }}/{{ war_file_name }}"
    dest: "{{ backup_dir }}/{{ war_file_name }}_{{ ansible_date_time.iso8601 }}.war"
    remote_src: yes

- name: Remove current WAR file
  shell: "rm -f {{ deploy_dir }}/{{ war_file_name }}*"

- name: Deploy the WAR file
  copy:
    src: "roles/jboss_deploy/files/{{ war_file_name }}"
    dest: "{{ deploy_dir }}/{{ war_file_name }}"

- name: Create .dodeploy file 
  shell: "touch {{ deploy_dir }}/{{ war_file_name }}.dodeploy"

- name: Check all Deployed files  
  shell: "ls -l  {{ deploy_dir }}/{{ war_file_name }}*"
  register: ls_output

- name: Display the files listed
  debug:
    #var: ls_output.stdout
    #msg: "{{ ls_output.stdout_lines | join('\n') }}"
    msg: "{{ ls_output.stdout }}"

- name: Starting the Jboss from shell 
  command: echo "Starting the Jboss from shell"


