---
- name: Ensure backup directory exists
  file:
    path: "{{ backup_dir }}"
    state: directory

# jboss-cli.sh --controller=localhost:9990 --connect --command=shutdown
- name: Stop JBoss service
  shell: "/opt/jboss/bin/jboss-cli.sh --controller=localhost:9990 --connect --command=shutdown"
  become_user: jboss
  environment:
    JAVA_HOME: "{{ java_home }}"
    JBOSS_HOME: "{{ jboss_home }}"

- name: Backup current deployment
  copy:
    src: "{{ deploy_dir }}/{{ war_file_name }}"
    dest: "{{ backup_dir }}/{{ war_file_name }}_{{ ansible_date_time.iso8601 }}.war"
    remote_src: yes

- name: Remove current WAR file
  file:
    path: "{{ deploy_dir }}/{{ war_file_name }}"
    state: absent

- name: Deploy the WAR file
  copy:
    src: "roles/jboss_deploy/files/{{ war_file_name }}"
    dest: "{{ deploy_dir }}/{{ war_file_name }}"

- name: Create .dodeploy file 
  shell: "touch {{ deploy_dir }}/{{ war_file_name }}.dodeploy"

- name: Stop JBoss service
  shell: "/opt/jboss/bin/standalone.sh -b 0.0.0.0"
  environment:
    JAVA_HOME: "{{ java_home }}"
    JBOSS_HOME: "{{ jboss_home }}"

