---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: viewer
rules:
    - apiGroups: ["*"]
      resources: ["deployment", "configmap", "pods", "secrets", "services" ]
      verbs: ["get", "list", "watch"]

