name: Ansible Playbook on EC2

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p  /home/runner/.ssh/
        touch /home/runner/.ssh/known_hosts
        echo "#" > ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Connect to EC2 and list directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          ls -l /home/ec2-user
          sudo sh -x /opt/jboss/ansible_com/rakassignment/ansible_deployment/run_playbook_jboss.sh &
          sleep 10
          ps -ef | grep -i jboss
          

 
#         ssh -i /home/runner/ec2_pemfile  ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'ls -l /home/ec2-user'
#/home/runner/.ssh/known_hosts
# ssh -i  /c/terr/terraform/aj-new-us-es-2.pem  ec2-user@18.222.222.145
# >> /home/runner/ec2_pemfile
        #echo ${{ secrets.EC2_SSH_KEY }} 
        