name: Build and Deploy WAR to Github Packages

on:
  workflow_dispatch:

jobs:
  build_and_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy demo1.zip (file genereated from start.spring.io)
        run: |
            cp demo1.zip demo.zip

      - name: unzip demo1.zip
        run: |
          unzip demo.zip

      - name: Copy index.jsp to src/main/webapp
        run: |
          cd demo1
          mkdir -p src/main/webapp
          cp ../index.jsp src/main/webapp/index.jsp

      - name: Copy new POM 
        run: |
          rm -f demo1/pom.xml
          cp pom.xml demo1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd demo1
          mvn clean package

      - name: Publish to GitHub Packages
        run: |
          cd demo1
          mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          
