
name: Build and Deploy WAR to Docker

on:
  push:
    branches:
      - main

jobs:
  build_and_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy demo1.zip (file genereated from start.spring.io)
        run: |
            cp demo1.zip demo.zip
#            mv demo.zip demo1.zip

      - name: unzip demo1.zip
        run: |
          unzip demo.zip

      - name: Copy index.jsp to src/main/webapp
        run: |
          cd demo1
          mkdir -p src/main/webapp
          cp ../index.jsp src/main/webapp/index.jsp


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd demo1
          mvn clean package

#      - name: Archive WAR file
#        uses: actions/upload-artifact@v3
#        with:
#          name: webapp-war
#          path: target/*.war#

#      #- name: Download WAR file
#        uses: actions/download-artifact@v3
#        with:
#          name: webapp-war
#          path: .

      - name: Copy Dockerfile
        run: |
          cp Dockerfile dockerfile

      - name: Build Docker Image
        run: |
          docker build -t my-webapp .

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 --name my-webapp-container my-webapp

      - name: Wait for Docker Container to Start
        run: sleep 15

      - name: Print Application URL
        run: echo "Application is running at http://localhost:8080"

      - name: See the Application page
        run: |
          curl http://localhost:8080


