
name: Deploy to EKS with Helm

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step to set up kubectl and aws-cli
    - name: Set up kubectl and aws-cli
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    # Step to fetch EKS kubeconfig
    - name: Fetch EKS kubeconfig
      run: aws eks --region us-east-2 update-kubeconfig --name staging-demo

    # Step to deploy with Helm
    - name: Deploy with Helm
      run: |
        helm install springboot-webapp ./springboot-webapp-0.1.0.tgz

