
name: Build and Deploy WAR to Docker

# this is working 

#on:
#  push:
#    branches:
#      - main

on:
  workflow_dispatch:

jobs:
  build_and_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy demo1.zip (file genereated from start.spring.io)
        run: |
            cp demo1.zip demo.zip

      - name: unzip demo1.zip
        run: |
          unzip demo.zip

      - name: Copy index.jsp to src/main/webapp
        run: |
          cd demo1
          mkdir -p src/main/webapp
          cp ../index.jsp src/main/webapp/index.jsp


      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'


      - name: Cache SonarCloud packages
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd demo1
          mvn clean verify sonar:sonar \
          -Dsonar.projectKey=rak_rak \
          -Dsonar.organization=rak \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}


      - name: Build with Maven
        run: |
          cd demo1
          mvn clean package

      - name: Copy Dockerfile
        run: |
          cp Dockerfile demo1/dockerfile

      # Step to set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step to log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step to build the Docker image
      - name: Build Docker image
        run: |
          cd demo1
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/rak:webapp .

      # Step to push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/rak:webapp

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 --name my-webapp-container ${{ secrets.DOCKER_HUB_USERNAME }}/rak:webapp

      - name: Wait for Docker Container to Start
        run: sleep 10

      - name: Print Application URL
        run: echo "Application is running at http://localhost:8080"

      - name: See the Application page
        run: |
          curl http://localhost:8080

