name: Pull WAR from Github Packages and Run on Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build_and_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Download WAR from GitHub Packages
        run: mvn dependency:get -DremoteRepositories=github::default::https://maven.pkg.github.com/ajveldhi/rakassignment -Dartifact=com.example1:demo1:0.0.1-SNAPSHOT:war -Dtransitive=false    
        env:
          GITHUB_USERNAME: ${{ secrets.GIT_USER }}
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
          
      - name: check downloaded file 
        run: |
          ls -lhtr ~/.m2/repository/com/example1/*
          ls -lthr ~/.m2/repository/com/example1/demo1/*
          echo "---"
          tree ~/.m2/repository/com/example1/*

#      - name: Verify package
#        run: ls -la ~/.m2/repository/groupId/artifactId/version # Adjust path based on package groupId, artifactId, and version

#      - name: Pull Maven package
#        run: mvn dependency:get -Dartifact=groupId:artifactId:version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step to build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/rak:webapp -f Dockerfile_for_Pull .

      - name: Run Docker Container
        run: |
          docker run -d -p 8080:8080 --name my-webapp-container ${{ secrets.DOCKER_HUB_USERNAME }}/rak:webapp

      - name: Wait for Docker Container to Start
        run: sleep 10

      - name: Print Application URL
        run: echo "Application is running at http://localhost:8080"

      - name: See the Application page
        run: |
          curl http://localhost:8080

          