name: Pull WAR to Github Packages

on:
  workflow_dispatch:

jobs:
  build_and_Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy demo1.zip (file genereated from start.spring.io)
        run: |
            cp demo1.zip demo.zip

      - name: unzip demo1.zip
        run: |
          unzip demo.zip

      - name: Copy new POM 
        run: |
          rm -f demo1/pom.xml
          cp pom.xml demo1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish to GitHub Packages
        run: |
          cd demo1
          mvn deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          

      - name: Pull Maven package
        run: mvn dependency:get -Dartifact=groupId:artifactId:version

      - name: Verify package
        run: ls -la ~/.m2/repository/groupId/artifactId/version # Adjust path based on package groupId, artifactId, and version