name: Pull from github packages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Download WAR from GitHub Packages
      run: mvn dependency:get -DremoteRepositories=github::default::https://maven.pkg.github.com/OWNER/REPOSITORY -Dartifact=com.example:your-app:1.0.0:war -Dtransitive=false
      env:
        GITHUB_USERNAME: ${{ secrets.GIT_USER }}
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}  
        
    - name: check downloaded file 
      run: |
        ls -ltr ~/.m2/repository/com/example1/*
        tree ~/.m2/repository/com/example1/*
        
        