name: Pull from github packages

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download WAR file from GitHub Packages
      uses: actions/download-artifact@v3
      with:
        name: demo1-0.0.1-SNAPSHOT.war  # Assuming artifact name is 'war-file'
        owner: ajveldhi  # Replace with your actual owner
        repo: rakassignment  # Replace with your actual repository
