name: Test ec2 with creds 1

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Add EC2 host to known_hosts
      run: |
        mkdir -p  /home/runner/.ssh/
        touch /home/runner/.ssh/known_hosts
        echo "#" > ~/.ssh/known_hosts
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Connect to EC2 and list directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_IP }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          ls -l /home/ec2-user


#/home/runner/.ssh/known_hosts